name: mywallet-api

services:
  api:
    image: mywallet
    container_name: mywallet-api
    build:
      context: .
      dockerfile: src/MyWallet/Dockerfile
    ports:
      - "5767:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    volumes:
      - ~/.microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  db:
    image: postgres
    container_name: mywallet-db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin" ]
      interval: 10s
      timeout: 30s
      retries: 5
    ports:
      - "5768:5432"
    environment:
      - POSTGRES_DB=mywallet
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - .data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"