global using ErrorOr;
global using FluentAssertions;
global using JetBrains.Annotations;
global using NSubstitute;
global using NSubstitute.ReceivedExtensions;
global using NSubstitute.ReturnsExtensions;
global using TestUtils.Constants;
global using TestUtils.Factories;
global using Xunit;